--  Configuration for stm32f746disco generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Stm32f746disco_Config is
   pragma Pure;

   Crate_Version : constant String := "0.1.0";
   Crate_Name : constant String := "stm32f746disco";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "ubuntu";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := release;

end Stm32f746disco_Config;
