--  Configuration for adl_middleware generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Adl_Middleware_Config is
   pragma Pure;

   Crate_Version : constant String := "0.4.0-dev";
   Crate_Name : constant String := "adl_middleware";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "ubuntu";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := release;

   Max_Mount_Points_First : constant :=  1;
   Max_Mount_Points_Last : constant :=  9223372036854775807;
   Max_Mount_Points : constant :=  2;

   Max_Path_Length_First : constant :=  1;
   Max_Path_Length_Last : constant :=  9223372036854775807;
   Max_Path_Length : constant :=  1024;

   Max_Mount_Name_Length_First : constant :=  1;
   Max_Mount_Name_Length_Last : constant :=  9223372036854775807;
   Max_Mount_Name_Length : constant :=  128;

end Adl_Middleware_Config;
