--  Configuration for stm32_hal generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Stm32_Hal_Config is
   pragma Pure;

   Crate_Version : constant String := "0.1.0";
   Crate_Name : constant String := "stm32_hal";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "ubuntu";

   type device_Kind is (stm32f746, stm32f429, stm32f407xx);
   device : constant device_Kind := stm32f746;

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := release;

end Stm32_Hal_Config;
