/* Configuration for stm32_hal generated by Alire */
#ifndef STM32_HAL_CONFIG_H
#define STM32_HAL_CONFIG_H

#define CRATE_VERSION "0.1.0"
#define CRATE_NAME "stm32_hal"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define DEVICE_STM32F746 1
#define DEVICE_STM32F429 2
#define DEVICE_STM32F407XX 3

#define DEVICE  1

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
